export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  COMPANY_PENDING: 'COMPANY_PENDING',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  TARIFF_LIMIT_EXCEEDED: 'TARIFF_LIMIT_EXCEEDED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FACE_NOT_FOUND: 'FACE_NOT_FOUND',
  /** Yuborilgan kadr(lar)da yuz aniqlanmadi — transient, qayta urinish mumkin */
  FACE_NOT_DETECTED: 'FACE_NOT_DETECTED',
  FACE_MULTIPLE: 'FACE_MULTIPLE',
  FACE_LOW_QUALITY: 'FACE_LOW_QUALITY',
  FACE_NOT_RECOGNIZED: 'FACE_NOT_RECOGNIZED',
  /** Enroll: yuklangan rasmdagi yuz allaqachon BOSHQA xodimga biriktirilgan */
  FACE_ALREADY_ENROLLED: 'FACE_ALREADY_ENROLLED',
  LIVENESS_FAILED: 'LIVENESS_FAILED',
  /** Aktiv liveness challenge (bosh burilishi/blink) bajarilmadi — transient */
  CHALLENGE_FAILED: 'CHALLENGE_FAILED',
  OUT_OF_GEOFENCE: 'OUT_OF_GEOFENCE',
  MOCK_LOCATION: 'MOCK_LOCATION',
  DEBOUNCE: 'DEBOUNCE',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  FACE_SERVICE_UNAVAILABLE: 'FACE_SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
